//
// Created by Alfonso Meraz on 12/5/20.
//

#ifndef STATISTICAL_FINANCIAL_DATA_STATES_H
#define STATISTICAL_FINANCIAL_DATA_STATES_H


enum states { SHOW, HIDE};


#endif //STATISTICAL_FINANCIAL_DATA_STATES_H
