//
// Created by Alfonso Meraz on 12/10/20.
//

#ifndef STATISTICAL_FINANCIAL_DATA_TTESTANALYSISITEM_H
#define STATISTICAL_FINANCIAL_DATA_TTESTANALYSISITEM_H


class TTestAnalysisItem {

};


#endif //STATISTICAL_FINANCIAL_DATA_TTESTANALYSISITEM_H
